"""Add patient vitals

Revision ID: 3afdeb4baeae
Revises: 5fe76e0791fd
Create Date: 2026-02-10 09:01:14.000285+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afdeb4baeae'
down_revision: Union[str, None] = '5fe76e0791fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('weight', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('height', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'height')
    op.drop_column('patients', 'weight')
    # ### end Alembic commands ###
