"""Add user auth

Revision ID: 473474038aaa
Revises: 3afdeb4baeae
Create Date: 2026-02-11 22:30:05.190144+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '473474038aaa'
down_revision: Union[str, None] = '3afdeb4baeae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # Checkpoint tables are managed by LangGraph / Raw SQL, not models. Do not drop.
    op.add_column('patients', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    op.add_column('sessions', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'user_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'user_id')
    # Checkpoint tables are managed by LangGraph / Raw SQL, not models. Do not recreate/drop.
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
